### ISSUE TITLE
Incorrect ReadMe Info

### ISSUE THREAD

**Issue by DuckBoss** [ForrestKnight/ConnectFour#2]
Hey, was checking out your repositories but this one has an incorrect title.
It says "Sudoku Solver" even though this is your "Connect Four" repo.

**Comment by DuckBoss** [comment]
Someone made a pull request addressing this issue: https://github.com/ForrestKnight/ConnectFour/pull/1

**Comment by ForrestKnight** [comment]
Thanks!
